version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "80:5000"
    volumes:
      - db-data:/app

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - db-data:/app

volumes:
  db-data: