FROM python:3.12

WORKDIR /app
ENV PYTHONPATH=.

COPY . .

RUN pip install -r requirements.txt

ENV FLASK_APP=app.py
ENV FLASK_ENV=development
# 0.0.0.0 allows access outside the Docker container, including from local host
CMD ["flask", "run", "--host=0.0.0.0"]